# Generated by Django 2.0.6 on 2018-06-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
