# Generated by Django 2.0.6 on 2018-06-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0002_grade_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='specialisation',
            new_name='specialization',
        ),
    ]
