# Generated by Django 2.0.6 on 2018-06-10 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0003_auto_20180607_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'get_latest_by': ['datetime'], 'ordering': ['datetime']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.AddField(
            model_name='lesson',
            name='taught',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolregister.Taught'),
        ),
    ]
