# Generated by Django 2.0.6 on 2018-06-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0004_auto_20180610_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schoolregister.Teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='taught',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schoolregister.Taught'),
            preserve_default=False,
        ),
    ]
