# Generated by Django 2.0.6 on 2018-06-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0005_auto_20180610_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
