# Generated by Django 2.0.6 on 2018-06-12 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0006_auto_20180610_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'get_latest_by': ['start_time'], 'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['student']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user']},
        ),
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
