# Generated by Django 2.0.6 on 2018-06-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0007_auto_20180612_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-datetime']},
        ),
    ]
