# Generated by Django 2.0.6 on 2018-06-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolregister', '0008_auto_20180613_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user']},
        ),
    ]
