# Generated by Django 2.0.6 on 2018-06-13 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_file_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='shared_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
