# Generated by Django 2.0.6 on 2018-06-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_share_shared_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='share',
            name='file',
        ),
        migrations.RemoveField(
            model_name='share',
            name='shared_to',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
